### ISSUE TITLE
Workspace buttons missaligned

### ISSUE THREAD

**Issue by lyze237** [lars-berger/GlazeWM#115]
Hey!

I have a 3 screen setup with multiple DPI scales and noticed that workspace buttons get misaligned sometimes and show partially offscreen:

3440x1440 with 100%
![image](https://user-images.githubusercontent.com/11274700/188065066-53eccf76-4cae-4da0-b28d-1cd69af8d4de.png)

2560x1440 with 150%
![image](https://user-images.githubusercontent.com/11274700/188065098-84da40ab-35d4-41a7-999c-12ece4972199.png)

1920x1080 with 100%
![image](https://user-images.githubusercontent.com/11274700/188064126-effbe404-2e43-4d82-853d-65caf06c2265.png)

It also seems like that this only happens with longer workspace names and not with "number only" workspaces.

Bar config:
```yaml
bar:
  height: 30
  position: "bottom"
  opacity: 1.0
  background: "#282A36"
  foreground: "#F8F8F2"
  font_family: "Segoe UI"
  font_size: "13"
  padding: "1 6 1 6"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#666B87"
      displayed_workspace_background: "#44475a"
      default_workspace_background: "#44475a"
  components_right:
    - type: "clock"
      time_formatting: "HH:mm - ddd dd MMM"
```
