### ISSUE TITLE
only first workspace is visible in title bar

### ISSUE THREAD

**Issue by azinsharaf** [lars-berger/GlazeWM#126]
Hi, I have configured 3 workspaces but i just see the first one. Please advise. 

```
workspaces:
  # Uniquely identifies the workspace and is used as the label for the workspace in the bar if
  # `display_name` is not provided.
  - name: 1

    # Optional override for the workspace label in the bar. Does not need to be unique.
    display_name: "1 Outlook/Teams"

    # Optionally force the workspace on a specific monitor if it exists. Use the monitor's number
    # as shown in the Windows display settings (eg. 1, 2, 3...).
    bind_to_monitor: 1
    
  - name: 2
    display_name: "2 Terminal"
    bind_to_monitor: 1
    
  - name: 3
    display_name: "3 ArcGIS"
    bind_to_monitor: 1
    
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
  - name: 9
```

![image](https://user-images.githubusercontent.com/10101468/189983917-c08ba3a1-8023-4d36-a0ce-7d85cae337b6.png)

**Comment by s-v-o** [comment]
Hi Azin,
when you are switching the workspace (default: alt+2), the new workspace is dynamically created. 
An empty worspace disposes automatically.

But I think there is now also a configuration option which could keep your workspaces alive (so that they are always visible):

```
workspaces:
  - name: 1
    display_name: "1"
    keep_alive: true
```
