### ISSUE TITLE
MS Teams notification popup

### ISSUE THREAD

**Issue by azinsharaf** [lars-berger/GlazeWM#129]
the notification window popup of MS Teams appears in the center of my screen instead of lower right which is the default Teams app setting. Any idea how it can be fixed?

**Comment by lars-berger** [comment]
The following window rule should fix it:

```yaml
window_rules:
  - command: "ignore"
    match_process_name: "Teams"
    match_title: "Microsoft Teams Notification"
```
