### ISSUE TITLE
Feature Request: save layout and content

### ISSUE THREAD

**Issue by verajosemanuel** [lars-berger/GlazeWM#143]
I usually work with the same apps: mail app and chat app on monitor 1, code editor and web browser on monitor 2. More workspaces added to every monitor as media player, spotify, and such.... 
Everytime I boot my pc I must open all apps and send to every workspace by hand.

Could be a great option to have to be able to save all apps and positions in every workspace and then reload whenever I need it (at boot)

Thanks

**Comment by lars-berger** [comment]
If you have a system for which workspaces should contain specific apps, you could write a window rule to automatically move them:

```yaml
workspaces:
  - name: "1"
    bind_to_monitor: 1
  - name: "2"
    bind_to_monitor: 2

window_rules:
  - command: "move to workspace 1"
    match_process_name: "code"
  - command: "move to workspace 2"
    match_process_name: "chrome"
```
