### ISSUE TITLE
Disable auto focus when moving application to another workspace

### ISSUE THREAD

**Issue by ColonelBucket8** [lars-berger/GlazeWM#146]
Hi, thanks for the awesome tiling window manager. Before this I used bugn but I like glazeWM more because of the way glazeWM handles workspaces like i3. My issue right now is, is there any way to disable auto focus when moving application to another workspace like i3? For example, with current behavior, if I move my application from workspace 1 to 2 (Alt + Shift +2), it will focus on workspace 2. I want the focus to stay on my current workspace 1.

**Comment by lars-berger** [comment]
Sure, it's a simple change to your config file (found at `C:\Users\<YOUR_USER>\.glaze-wm\config.yaml`).

In the default config, pressing Alt+Shift+1 invokes both `move to workspace 1` + `focus workspace 1`. Change these keybindings to only invoke `move to workspace X`, like so:

```yaml
  // Change from ["move to workspace 1", "focus workspace 1"] to:
  - commands: ["move to workspace 1"] 
    binding: "Alt+Shift+1"
    ...
```
