### ISSUE TITLE
Color focused workspace border in status bar

### ISSUE THREAD

**Issue by ColonelBucket8** [lars-berger/GlazeWM#152]
Is there any way to color one specific focused workspace border in status bar? Right now, you can only color all border workspaces as shown below.
![image](https://user-images.githubusercontent.com/59568628/197372791-8b25c6a3-e3a4-452a-a21f-7b6a50dea7eb.png)

**Comment by lars-berger** [comment]
The color and width of borders can be changed for the different states, like so:

```yaml
bar:
  components_left:
    - type: "workspaces"
      focused_workspace_border_color: "blue"
      focused_workspace_border_width: "2"
      displayed_workspace_border_color: "yellow"
      displayed_workspace_border_width: "3"
      default_workspace_border_color: "red"
      default_workspace_border_width: "4"
```
