### ISSUE TITLE
Feature Request: binding modes

### ISSUE THREAD

**Issue by kress95** [lars-berger/GlazeWM#181]
Props for creating what is probably the "KISSest" tiling WM for windows, a great experience so far.

I know this is probably not meant to be a full i3 clone, but it would be really nice to have [binding modes](https://i3wm.org/docs/userguide.html#binding_modes)

**Comment by lars-berger** [comment]
Yeah I agree that binding modes are a really nice feature from i3. 

It's not too technically challenging to implement, but I'm not sure about how to clearly represent it in the config. First thought is something like this:

```yaml
keybindings:
  - command: "activate mode resize"
    binding: "Alt+R"
    
modes:
  - name: resize
    keybindings:
      - command: "resize width -2%"
        binding: "L"
      - command: "resize width +2%"
        binding: "H"
      - command: "resize height +2%"
        binding: "K"
      - command: "resize height -2%"
        binding: "J"
      - command: "deactivate mode resize"
        binding: "Escape"
```
