### ISSUE TITLE
window_rules whitelist

### ISSUE THREAD

**Issue by sealevelcain** [lars-berger/GlazeWM#188]
I don't want tiling to be the default behaviour and would only like to apply it to File Explorer and Firefox windows - is there a way to apply tiling rules on a whitelist basis so I don't have to list every other app/process under the ignore command?

**Comment by lars-berger** [comment]
You could use a regex to select all windows except firefox/explorer, eg:

```yaml
window_rules:
  - command: "ignore"
    match_process_name: "/^(?!(firefox|explorer)$)/"
```

`set floating` might be a better option than `ignore` depending on your use case (keybindings don't fire if an ignored window has focus).
