### ISSUE TITLE
set height/width Unhandled exception: Value does not fall within the expected range. (Parameter 'commandParts'))

### ISSUE THREAD

**Issue by momozahara** [lars-berger/GlazeWM#279]
version 1.11.1

``` yaml
window_rules:
  - command: "set width 800px"
    match_process_name: "Spotify"
````
