### ISSUE TITLE
Move workspace to monitor

### ISSUE THREAD

**Issue by felipecrp** [lars-berger/GlazeWM#342]
Hi,

It would be great if we could move the workspace to a specific monitor. 

I know that I can bind the workspace to monitor, but it would be better if we could dynamically arrange the workspaces. In a notebook, sometimes I need to connect to an external monitor and would like to move a specific workspace to that monitor.

Regards,

**Comment by adriafarres** [comment]
You can already do that. For example,
```yaml
keybindings:
  - command: "move workspace left"
    binding: "Alt+LWin+H"

  - command: "move workspace right"
    binding: "Alt+LWin+L"

```
