### ISSUE TITLE
Separate opened windows to separate workspaces at launch of glazewm

### ISSUE THREAD

**Issue by BrandonBlankerLim-it** [lars-berger/GlazeWM#46]

**Comment by lars-berger** [comment]
I agree that the initial launch can be messy if there's loads of windows already opened. Do you have a suggestion on how the windows could be separated?

Do you typically minimize a lot of apps? I reckon part of the problem stems from the fact that minimized apps are restored on launch. 

If in your case, you have a system for which workspaces should contain specific apps, you could also write a window rule to automatically move them:

```yaml
window_rules:
  - command: "move to workspace 4"
    match_process_name: "chrome"
```
