### ISSUE TITLE
Exclude dialog boxes by default

### ISSUE THREAD

**Issue by scubamount** [lars-berger/GlazeWM#58]
In relation to a similar issue, is there a class or match_title that could be implemented like this? If I could find out how to universally exclude things like explorer or dialog popups, I would submit a pull

**Comment by nascentt** [comment]
I think I know what you're referring to however from my experience if a window cannot be resized (ie a fixed dialog) GLazeWM will not tile it but instead center it on the screen above any tiled windows (example start> run).  which to me is the perfect behavior.

What I think you're referring to is the tiling of resizable dialogs such as Open and Save As dialogs?

I just created some rules for this which seem to work for me.  They can probably be further filtered to prevent false positives, but at least these catch the open and save dialogs I have tested.
```
window_rules:
  - command: "ignore"
    match_title: "/.*Save As.*/"
  - command: "ignore"
    match_title: "/.*Open.*/"
```
