### ISSUE TITLE
Keepass 2

### ISSUE THREAD

**Issue by nascentt** [lars-berger/GlazeWM#61]
keepass 2 is exhibiting weird behavior where dialogs and settings randomly seem to get selected themselves, opening menus automatically close with things being selected.  It seems like a similar situation to notepad++ where glazewm is interacting and controlling with keepass 2. 
I tried to just create a window rule myself, but it'd be nice not to have to completely ignore the program from glazewm.

reproducible:

opening keepass 2 automatically tries to create a new entry as if "add entry" was pressed.
opening the fle menu automatically opens a search wizard
opening the tools menu opens the password generator automatically
...

**Comment by lars-berger** [comment]
As a temporary fix, this window rule seems to do the job:

```yaml
window_rules:
  - command: "ignore"
    match_class_name: "WindowsForms10.Window.20808.app.0.30495d1_r6_ad1"
```
It's definitely similar to the Notepad++ issue, but the menu windows that Keypass spawns have very different window styles compared to notepad++. Will see if the logic for deciding whether to manage a window can be changed to prevent similar issues in the future.
