### ISSUE TITLE
Array support for match_process_name

### ISSUE THREAD

**Issue by crimist** [lars-berger/GlazeWM#81]
Small improvement for config, support arrays for `match_process_name`.

```yaml
# before
window_rules:
  # ignore foo.exe
  - command: "ignore"
    match_process_name: "foo"
  # ignore bar.exe
  - command: "ignore"
    match_process_name: "bar"  

# after
window_rules:
  # ignore foo.exe and bar.exe
  - command: "ignore"
    match_process_name: ["foo", "bar"]
```

Great WM :)

**Comment by lars-berger** [comment]
It's possible to avoid specifying multiple window rules for your use case by using regex, eg:

```yaml
window_rules:
  # ignore foo.exe and bar.exe
  - command: "ignore"
    match_process_name: "/foo|bar/"
```
